import React, { useContext, useState } from "react";
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { UserContext } from "../../context/userContext";
import Dashboard from "../Home/Dashboard";

const LandingPage = () => {
  const {user}=useContext(UserContext);
  const navigate = useNavigate();

  useEffect(()=>{
    console.log("This is Landing Page",user);
  },[user])

//   useEffect(()=>{
// console.log("AfterLogout",user);
//   },[])

  const handleLogout=()=>{

  }
  const handleDashboard=()=>{
    navigate("/dashboard");
  }
  return (
    <div className="min-h-screen bg-linear-to-br from-[#fff8ec] to-[#fffef7] text-gray-900 flex flex-col">
      {/* Navbar */}
      <header className="flex justify-between items-center px-6 md:px-16 py-4">
        <h1 className="text-xl font-semibold tracking-tight">
          Interview Prep <span className="text-black">AI</span>
        </h1>
        { user ?<>
          <div onClick={handleDashboard} className="cursor-pointer bg-black text-white px-4 py-2 rounded-3xl font-medium hover:text-orange-200">
            Dashboard
          </div>
          <div className="flex items-center gap-3">
          <img
            src={user.reloadUserInfo.photoUrl?user.reloadUserInfo.photoUrl:"https://i.pinimg.com/564x/57/00/c0/5700c04197ee9a4372a35ef16eb78f4e.jpg"}
            alt="User"
            className="w-10 h-10 rounded-full border"
          />
          <div >
            <p className="font-semibold text-gray-800">{user.displayName}</p>
            {/* <p className="font-semibold text-gray-400 text-[10px]">{user.email}</p> */}
            <button onClick={handleLogout} className="text-sm text-orange-500 font-medium hover:underline">
              Logout
            </button>
            
          </div>
        </div> </>:
        
        <button
          onClick={() => navigate("/login")}
          className="bg-linear-to-r from-[#ffb347] to-[#ffcc33] text-black font-medium px-4 py-2 rounded-full hover:opacity-90 transition"
        >
          Login / Sign Up
        </button>
        }
      </header>

      {/* Hero Section */}
      <section className="flex flex-col md:flex-row items-center justify-between px-6 md:px-20 py-16 grow">
        {/* Left Content */}
        <div className="max-w-xl text-center md:text-left space-y-5">
          <div className="inline-flex items-center bg-[#fff1cc] text-[#d97706] px-3 py-1 rounded-full text-sm font-medium">
            ⚡ AI Powered
          </div>

          <h2 className="text-4xl md:text-5xl font-bold leading-tight text-gray-900">
            Ace Interviews with{" "}
            <span className="text-[#ff9900]">AI-Powered Learning</span>
          </h2>

          <p className="text-gray-600 text-base md:text-lg">
            Get role-specific questions, expand answers when you need them, dive
            deeper into concepts, and organize everything your way — your
            ultimate interview toolkit is here.
          </p>

          <button
            onClick={() => navigate("/login")}
            className="bg-black text-white px-6 py-3 rounded-full font-medium hover:bg-gray-800 transition"
          >
            Get Started
          </button>
        </div>

        {/* Optional Image */}
        <div className="hidden md:block w-[45%]">
          <img
            src="https://www.interviewigniter.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fai-tools.ca3dfe88.jpg&w=2048&q=75"
            alt="Interview Illustration"
            className="w-full h-auto rounded-2xl shadow-lg"
          />
        </div>
      </section>

      {/* Features Section */}
      <section className="bg-[#fffaf0] py-16 px-6 md:px-20">
        <h3 className="text-3xl font-semibold text-center mb-10">
          Features That Make You Shine
        </h3>

        <div className="grid md:grid-cols-2 lg:grid-cols-2 gap-12">
          {[
            {
              title: "Tailored Just for You",
              desc: "Get interview questions and model answers based on your role, experience, and focus areas — no generic practice here.",
            },
            {
              title: "Learn at Your Own Pace",
              desc: "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
            },
           
            {
              title: "Understand the 'Why' Behind Answers",
              desc: "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.",
            },
            {
              title: "Save, Organize, and Revisit",
              desc: "Easily save your interview sets, organize them neatly in your dashboard, and pick up right where you left off.",
            },
          ].map((item, i) => (
            <div
              key={i}
              className="bg-white shadow-md rounded-2xl p-6 hover:shadow-lg transition"
            >
              <h4 className="font-semibold text-lg mb-2">{item.title}</h4>
              <p className="text-gray-600 text-sm">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="py-6 text-center text-gray-500 text-sm border-t mt-auto">
        © {new Date().getFullYear()} Interview Prep AI. All rights reserved.
      </footer>
    </div>
  );
};

export default LandingPage;
